name: chartiq_flutter_sdk
description: ChatIQ Flutter SDK
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chartiq.chartiq_flutter_sdk
        pluginClass: ChartiqFlutterSdkPlugin
      ios:
        pluginClass: ChartiqFlutterSdkPlugin