name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v$

      # For Flutter package
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.13.1'
      - name: Install dependencies
        run: flutter pub get

      - name: Publish
        run: flutter pub publish --force